service: getName

provider:
  name: aws
  deploymentMethod: direct
  stage: dev
  region: af-south-1
  runtime: python3.10
  timeout: 29
  layers:
    - Ref: PythonRequirementsLambdaLayer
  tracing:
    apiGateway: true
  tags:
    ENVIRONMENT: dev

useDotenv: true

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

functions:
  getName:
    handler: src/api/getName.handler
    events:
      - http:
          path: /name
          method: get

  getNameWithPrefix:
    handler: src/api/getNameWithPrefix.handler
    events:
      - http:
          path: /name/{prefix}
          method: get

package:
  patterns:
    - '!**'
    - 'src/**'

plugins:
  - serverless-python-requirements
  - serverless-offline
