service: demo

provider:
  name: aws
  deploymentMethod: direct
  stage: dev
  region: eu-west-1
  tracing:
    apiGateway: true

functions:
  demo:
    image:
      uri: 061379176831.dkr.ecr.eu-west-1.amazonaws.com/demo:latest
      command:
        - 'helloworld.App::handleRequest'
    events:
      - http:
          path: /howdy
          method: get
